export { default as Home } from './Home.view'
export { default as NewAuthor } from './NewAuthor.view'
export {default as NewComic} from './NewComic.view'
export {default as NewChapter} from './NewChapter.view'
export { default as Pages } from './pagesView/Pages.view'
