export { default as Home } from './Home.view'
export { default as NewAuthor } from './NewAuthor.view'
export {default as NewComic} from './NewComic.view'
export {default as NewChapter} from './NewChapter.view'
export {default as ComicView} from './ComicView/Comic.view'
export { default as Pages } from './pagesView/Pages.view'
export { default as TestComics } from './Test.view'
export { default as ComicsView } from "./ComicsView/Comics.view"
export { default as SignIn } from './Login/SignIn'
export { default as SignUp } from './Login/SignUp'
export {default as Profile} from './profile/Profile'
export { default as MyComics } from './myComics/MyComics.view'
export { default as UpdateComic } from './UpdateComic.view'
export {default as AdminPanel} from './Admin/AdminPanel'
